[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false
idl = true

[programs.localnet]
vdr_contract = "6ecWPUK87zxwZP2pARJ75wbpCka92mYSGP1szrJxzAwo"

[programs.devnet]
vdr_contract = "6ecWPUK87zxwZP2pARJ75wbpCka92mYSGP1szrJxzAwo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
